import Link from "next/link";
import type { Metadata } from "next";
import ThemeToggle from "../components/ThemeToggle";

export const metadata: Metadata = {
  title: "Terms of Service | CCR - Credit Card Recommender",
  description:
    "Review CCR's Terms of Service, affiliate disclaimers, and financial accuracy notices.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <main className="site-shell">
      <nav className="topbar" aria-label="Main navigation">
        <Link className="wordmark" href="/" aria-label="CCR home">
          <span className="wordmark-mark">C</span>
          <span>
            CCR <small>Credit Card Recommender</small>
          </span>
        </Link>
        <div className="topbar-right">
          <Link href="/" className="back-link">
            ← Back to Recommender
          </Link>
          <ThemeToggle />
        </div>
      </nav>

      <article className="legal-container">
        <div className="legal-header">
          <p className="eyebrow">Legal &amp; Disclosures</p>
          <h1>Terms of Service</h1>
          <p className="legal-date">Last Updated: August 2026</p>
        </div>

        <div className="legal-content">
          <section className="legal-section highlight-box">
            <h2>1. Informational Purposes Only (Not Financial Advice)</h2>
            <p>
              The calculations, estimates, reward multipliers, and net benefit values generated by CCR are provided
              solely for informational, educational, and comparison purposes. CCR is not a registered financial advisor,
              banking institution, or credit bureau. Always review the Most Important Terms and Conditions (MITC)
              directly on the issuing bank&apos;s official portal before applying.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Affiliate Disclosures</h2>
            <p>
              CCR participates in affiliate referral programs. When you click an &ldquo;Apply Now&rdquo; link and receive an
              approved card, we may earn an affiliate commission from partner networks or issuers. This commission comes at
              no additional cost to you. Our ranking algorithm remains strictly mathematical, scoring cards solely by
              projected net annual return and income eligibility.
            </p>
          </section>

          <section className="legal-section">
            <h2>3. Calculation Methodology &amp; Reward Caps</h2>
            <p>
              Estimates are derived by multiplying your monthly spending profile by the card&apos;s published reward rate,
              applying monthly milestone/category reward caps, annualizing the gross reward, and subtracting the base annual
              membership fee. Taxes (e.g. 18% GST on annual fees), rotating promotional rates, and welcome vouchers may vary
              by issuer.
            </p>
          </section>

          <section className="legal-section">
            <h2>4. Approval Signals &amp; Eligibility</h2>
            <p>
              The &ldquo;High chance of approval&rdquo; and &ldquo;Eligible to apply&rdquo; labels reflect baseline income threshold
              checks. Actual approval is strictly at the sole discretion of the issuing bank based on your comprehensive credit
              profile (CIBIL/Experian score), existing debt-to-income ratio, and internal underwriting policies.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. Trademark &amp; Brand Disclaimers</h2>
            <p>
              All bank names, card names, trademarks, and logos are the property of their respective owners (e.g., HDFC Bank,
              Axis Bank, SBI Card, ICICI Bank, American Express). Their mention on CCR is purely nominative and does not imply
              direct endorsement or formal affiliation.
            </p>
          </section>

          <section className="legal-section">
            <h2>6. Limitation of Liability</h2>
            <p>
              Under no circumstances shall CCR or its operators be liable for any discrepancies in card terms, changes in reward
              schedules by issuers, application rejections, or financial decisions made based on this tool.
            </p>
          </section>
        </div>
      </article>

      <footer className="site-footer" role="contentinfo">
        <div className="site-footer-inner">
          <div className="footer-top-grid">
            <div className="footer-brand-col">
              <div className="footer-brand-header">
                <div className="footer-logo-badge">CCR</div>
                <div>
                  <span className="footer-title">CCR Recommendation Engine</span>
                  <span className="footer-tagline">Zero-PII Credit Card Optimizer for India</span>
                </div>
              </div>
              <p className="footer-disclaimer">
                100% anonymous &amp; client-side calculation model. No personal identifying information is ever stored or transmitted.
              </p>
            </div>
            <div className="footer-nav-groups">
              <div className="footer-nav-col">
                <h4 className="footer-nav-heading">Platform</h4>
                <Link href="/">Recommender Home</Link>
                <Link href="/#faq">FAQs</Link>
              </div>
              <div className="footer-nav-col">
                <h4 className="footer-nav-heading">Legal</h4>
                <Link href="/privacy">Privacy Policy</Link>
                <Link href="/terms">Terms of Service</Link>
              </div>
            </div>
          </div>
          <div className="footer-bottom-bar">
            <p className="footer-copyright">&copy; 2026 CCR. Zero tracking &amp; client-side simulated.</p>
            <Link href="/" className="footer-back-to-top">Back to Recommender &uarr;</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}
