import type { Card } from "./cardTypes";

export const VERIFIED_CARDS: Card[] = [
  {
    id: "bobcard-eterna",
    bankName: "BOBCARD",
    cardName: "BOBCARD Eterna Credit Card",
    annualFee: 2499,
    minIncome: 1200000,
    imageUrl: "https://placehold.co/320x200?text=BOBCARD+Eterna",
    applyUrl: "https://bitli.in/zfq2tcW",
    multipliers: [
      { category: "Travel", rewardRate: 0.0375, maxCap: null },
      { category: "Dining", rewardRate: 0.0375, maxCap: null },
      { category: "Other", rewardRate: 0.0075, maxCap: null },
    ],
  },
  {
    id: "idfc-first",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC First Credit Card",
    annualFee: 0,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=IDFC+First",
    applyUrl: "https://bitli.in/hx5hmCd",
    multipliers: [
      { category: "Dining", rewardRate: 0.025, maxCap: null },
      { category: "Travel", rewardRate: 0.025, maxCap: null },
      { category: "Online", rewardRate: 0.015, maxCap: null },
      { category: "Other", rewardRate: 0.0025, maxCap: null },
    ],
  },
  {
    id: "sbm-zet",
    bankName: "SBM Bank",
    cardName: "SBM ZET Credit Card",
    annualFee: 0,
    minIncome: 0,
    imageUrl: "https://placehold.co/320x200?text=SBM+ZET",
    applyUrl: "https://www.sbmbank.co.in/personal-banking/cards/credit-cards",
    multipliers: [
      { category: "Online", rewardRate: 0.02, maxCap: 500 },
      { category: "Utilities", rewardRate: 0.02, maxCap: 300 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-neo",
    bankName: "Axis Bank",
    cardName: "Axis Neo Rupay Credit Card",
    annualFee: 250,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Neo",
    applyUrl: "https://bitli.in/6LmgmqG",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 200 },
      { category: "Dining", rewardRate: 0.05, maxCap: 200 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "roarbank-rupay",
    bankName: "RoarBank",
    cardName: "RoarBank Rupay Credit Card",
    annualFee: 0,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=RoarBank",
    applyUrl: "https://bitli.in/b4zeivA",
    multipliers: [
      { category: "Online", rewardRate: 0.02, maxCap: 400 },
      { category: "Utilities", rewardRate: 0.02, maxCap: 300 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "scapia-federal",
    bankName: "Federal Bank",
    cardName: "Scapia Co-Branded Credit Card",
    annualFee: 0,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=Scapia+Federal",
    applyUrl: "https://bitli.in/t7CElb2",
    multipliers: [
      { category: "Travel", rewardRate: 0.20, maxCap: null },
      { category: "Other", rewardRate: 0.10, maxCap: null },
    ],
  },
  {
    id: "hdfc-pixel-play",
    bankName: "HDFC Bank",
    cardName: "HDFC Pixel Play Credit Card",
    annualFee: 0,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Pixel+Play",
    applyUrl: "https://www.hdfcbank.com/personal/pay/cards/pixel-play-credit-card",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 1000 },
      { category: "Online", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "hdfc-pixel-go",
    bankName: "HDFC Bank",
    cardName: "HDFC Pixel Go Credit Card",
    annualFee: 0,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Pixel+Go",
    applyUrl: "https://bitli.in/LDb798j",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 750 },
      { category: "Online", rewardRate: 0.03, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "kotak-league",
    bankName: "Kotak Mahindra Bank",
    cardName: "Kotak League Platinum Credit Card",
    annualFee: 499,
    minIncome: 500000,
    imageUrl: "https://placehold.co/320x200?text=Kotak+League",
    applyUrl: "https://bitli.in/t53OuXc",
    multipliers: [
      { category: "Travel", rewardRate: 0.0125, maxCap: null },
      { category: "Other", rewardRate: 0.0125, maxCap: null },
    ],
  },
  {
    id: "hsbc-platinum",
    bankName: "HSBC Bank",
    cardName: "HSBC Platinum Credit Card",
    annualFee: 0,
    minIncome: 400000,
    imageUrl: "https://placehold.co/320x200?text=HSBC+Platinum",
    applyUrl: "https://bitli.in/LHo2ve3",
    multipliers: [
      { category: "Dining", rewardRate: 0.05, maxCap: 1000 },
      { category: "Travel", rewardRate: 0.03, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "dcb-novio",
    bankName: "DCB Bank",
    cardName: "DCB Novio Credit Card",
    annualFee: 0,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=DCB+Novio",
    applyUrl: "https://bitli.in/lFGhUdc",
    multipliers: [
      { category: "Online", rewardRate: 0.03, maxCap: 500 },
      { category: "Shopping", rewardRate: 0.02, maxCap: 300 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-flipkart",
    bankName: "Axis Bank",
    cardName: "Axis Flipkart Credit Card",
    annualFee: 500,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Flipkart",
    applyUrl: "https://bitli.in/3xH2lbI",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: null },
      { category: "Travel", rewardRate: 0.04, maxCap: null },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "indusind-tiger",
    bankName: "IndusInd Bank",
    cardName: "Indusind Tiger Credit Card",
    annualFee: 0,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=Indusind+Tiger",
    applyUrl: "https://bitli.in/X3x74f5",
    multipliers: [
      { category: "Travel", rewardRate: 0.03, maxCap: 600 },
      { category: "Shopping", rewardRate: 0.02, maxCap: 400 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-privilege-amex",
    bankName: "Axis Bank",
    cardName: "Axis Privilege Amex Credit Card",
    annualFee: 1500,
    minIncome: 600000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Privilege+Amex",
    applyUrl: "https://bitli.in/94IFi7f",
    multipliers: [
      { category: "Travel", rewardRate: 0.06, maxCap: null },
      { category: "Dining", rewardRate: 0.04, maxCap: null },
      { category: "Other", rewardRate: 0.02, maxCap: null },
    ],
  },
  {
    id: "hdfc-rupay",
    bankName: "HDFC Bank",
    cardName: "HDFC RuPay Credit Card",
    annualFee: 250,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+RuPay",
    applyUrl: "https://bitli.in/5f7ZcjU",
    multipliers: [
      { category: "Online", rewardRate: 0.03, maxCap: 500 },
      { category: "Grocery", rewardRate: 0.03, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-myzone",
    bankName: "Axis Bank",
    cardName: "Axis MyZone Rupay Credit Card",
    annualFee: 500,
    minIncome: 250000,
    imageUrl: "https://placehold.co/320x200?text=Axis+MyZone",
    applyUrl: "https://bitli.in/PCwxGT2",
    multipliers: [
      { category: "Dining", rewardRate: 0.04, maxCap: 480 },
      { category: "Shopping", rewardRate: 0.02, maxCap: 300 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-privilege",
    bankName: "Axis Bank",
    cardName: "Axis Privilege Credit Card",
    annualFee: 1500,
    minIncome: 600000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Privilege",
    applyUrl: "https://bitli.in/Dgkape0",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 1000 },
      { category: "Travel", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.02, maxCap: null },
    ],
  },
  {
    id: "idfc-first-power-plus",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC First Power Plus Credit Card",
    annualFee: 499,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=IDFC+Power+Plus",
    applyUrl: "https://bitli.in/SyhzA8D",
    multipliers: [
      { category: "Fuel", rewardRate: 0.065, maxCap: 1000 },
      { category: "Shopping", rewardRate: 0.02, maxCap: 500 },
      { category: "Dining", rewardRate: 0.02, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-cashback",
    bankName: "Axis Bank",
    cardName: "Axis Cashback Credit Card",
    annualFee: 500,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Cashback",
    applyUrl: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-cashback-credit-card",
    multipliers: [
      { category: "Online", rewardRate: 0.05, maxCap: 1000 },
      { category: "Shopping", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "idfc-mayura",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC FIRST Bank Mayura Credit Card",
    annualFee: 0,
    minIncome: 600000,
    imageUrl: "https://placehold.co/320x200?text=IDFC+Mayura",
    applyUrl: "https://bitli.in/BAsE98y",
    multipliers: [
      { category: "Travel", rewardRate: 0.06, maxCap: null },
      { category: "Dining", rewardRate: 0.04, maxCap: null },
      { category: "Other", rewardRate: 0.02, maxCap: null },
    ],
  },
  {
    id: "sbi-simplyclick",
    bankName: "SBI Card",
    cardName: "SBI Simply Click Credit Card",
    annualFee: 499,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=SBI+SimplyClick",
    applyUrl: "https://www.sbicard.com/en/personal/credit-cards/shopping/simplyclick-sbi-card.page",
    multipliers: [
      { category: "Shopping", rewardRate: 0.025, maxCap: null },
      { category: "Online", rewardRate: 0.0125, maxCap: null },
      { category: "Other", rewardRate: 0.0025, maxCap: null },
    ],
  },
  {
    id: "sbi-elite",
    bankName: "SBI Card",
    cardName: "SBI Elite Credit Card",
    annualFee: 4999,
    minIncome: 900000,
    imageUrl: "https://placehold.co/320x200?text=SBI+Elite",
    applyUrl: "https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page",
    multipliers: [
      { category: "Dining", rewardRate: 0.05, maxCap: 1250 },
      { category: "Travel", rewardRate: 0.05, maxCap: 1250 },
      { category: "Shopping", rewardRate: 0.03, maxCap: 750 },
      { category: "Other", rewardRate: 0.0125, maxCap: null },
    ],
  },
  {
    id: "sbi-cashback",
    bankName: "SBI Card",
    cardName: "SBI Cashback Credit Card",
    annualFee: 999,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=SBI+Cashback",
    applyUrl: "https://www.sbicard.com/en/personal/credit-cards/cashback-sbi-card.html",
    multipliers: [
      { category: "Online", rewardRate: 0.05, maxCap: 2000 },
      { category: "Other", rewardRate: 0.01, maxCap: 2000 },
    ],
  },
  {
    id: "axis-rewards",
    bankName: "Axis Bank",
    cardName: "Axis Rewards Visa Credit Card",
    annualFee: 1000,
    minIncome: 360000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Rewards",
    applyUrl: "https://bitli.in/yn6JHLq",
    multipliers: [
      { category: "Shopping", rewardRate: 0.04, maxCap: 1000 },
      { category: "Dining", rewardRate: 0.04, maxCap: 600 },
      { category: "Other", rewardRate: 0.015, maxCap: null },
    ],
  },
  {
    id: "hdfc-marriott",
    bankName: "HDFC Bank",
    cardName: "HDFC Bank Marriott Credit Card",
    annualFee: 3000,
    minIncome: 1200000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Marriott",
    applyUrl: "https://bitli.in/qgMB9Ob",
    multipliers: [
      { category: "Travel", rewardRate: 0.08, maxCap: null },
      { category: "Dining", rewardRate: 0.05, maxCap: null },
      { category: "Other", rewardRate: 0.02, maxCap: null },
    ],
  },
  {
    id: "sbi-flipkart",
    bankName: "SBI Card",
    cardName: "SBI Flipkart Credit Card",
    annualFee: 500,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=SBI+Flipkart",
    applyUrl: "https://bitli.in/i10Xr0Z",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: null },
      { category: "Online", rewardRate: 0.04, maxCap: null },
      { category: "Other", rewardRate: 0.02, maxCap: null },
    ],
  },
  {
    id: "sbi-simplysave",
    bankName: "SBI Card",
    cardName: "SBI Simply Save Credit Card",
    annualFee: 499,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=SBI+SimplySave",
    applyUrl: "https://www.sbicard.com/en/personal/credit-cards/shopping/simplysave-sbi-card.page",
    multipliers: [
      { category: "Shopping", rewardRate: 0.025, maxCap: null },
      { category: "Other", rewardRate: 0.0025, maxCap: null },
    ],
  },
  {
    id: "hdfc-swiggy",
    bankName: "HDFC Bank",
    cardName: "HDFC Swiggy Ornge Credit Card",
    annualFee: 500,
    minIncome: 180000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Swiggy",
    applyUrl: "https://bitli.in/wUdobzG",
    multipliers: [
      { category: "Dining", rewardRate: 0.10, maxCap: 1500 },
      { category: "Online", rewardRate: 0.05, maxCap: 1500 },
      { category: "Other", rewardRate: 0.01, maxCap: 500 },
    ],
  },
  {
    id: "idfc-wow-black",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC FIRST Wow Black Credit Card",
    annualFee: 0,
    minIncome: 0,
    imageUrl: "https://placehold.co/320x200?text=IDFC+Wow+Black",
    applyUrl: "https://bitli.in/gN2fmsy",
    multipliers: [
      { category: "Shopping", rewardRate: 0.03, maxCap: 600 },
      { category: "Online", rewardRate: 0.03, maxCap: 600 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "hdfc-irctc",
    bankName: "HDFC Bank",
    cardName: "HDFC IRCTC Credit Card",
    annualFee: 500,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+IRCTC",
    applyUrl: "https://bitli.in/iOx8cpq",
    multipliers: [
      { category: "Travel", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "hdfc-millennia",
    bankName: "HDFC Bank",
    cardName: "HDFC Millennia Credit Card",
    annualFee: 1000,
    minIncome: 420000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Millennia",
    applyUrl: "https://bitli.in/14ytBA7",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 1000 },
      { category: "Online", rewardRate: 0.05, maxCap: 1000 },
      { category: "Dining", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: 1000 },
    ],
  },
  {
    id: "kotak-cashback",
    bankName: "Kotak Mahindra Bank",
    cardName: "Kotak Cashback Plus Credit Card",
    annualFee: 500,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=Kotak+Cashback",
    applyUrl: "https://bitli.in/0YlNS9P",
    multipliers: [
      { category: "Online", rewardRate: 0.05, maxCap: 750 },
      { category: "Shopping", rewardRate: 0.03, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "rbl-shoprite",
    bankName: "RBL Bank",
    cardName: "RBL Bank Shoprite Credit Card",
    annualFee: 500,
    minIncome: 200000,
    imageUrl: "https://placehold.co/320x200?text=RBL+Shoprite",
    applyUrl: "https://bitli.in/jDtMo8J",
    multipliers: [
      { category: "Grocery", rewardRate: 0.05, maxCap: 1000 },
      { category: "Shopping", rewardRate: 0.03, maxCap: 600 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "hdfc-tataneu",
    bankName: "HDFC Bank",
    cardName: "Tata Neu HDFC Bank Credit Card",
    annualFee: 1499,
    minIncome: 1200000,
    imageUrl: "https://placehold.co/320x200?text=Tata+Neu+HDFC",
    applyUrl: "https://www.hdfcbank.com/personal/pay/cards/tata-neu-infinity-hdfc-bank-credit-card",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: null },
      { category: "Other", rewardRate: 0.015, maxCap: null },
    ],
  },
  {
    id: "idfc-wow",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC FIRST WOW Credit Card",
    annualFee: 0,
    minIncome: 0,
    imageUrl: "https://placehold.co/320x200?text=IDFC+WOW",
    applyUrl: "https://bitli.in/Ftsw1jM",
    multipliers: [
      { category: "Shopping", rewardRate: 0.01, maxCap: null },
      { category: "Other", rewardRate: 0.005, maxCap: null },
    ],
  },
  {
    id: "hdfc-shoppers-stop",
    bankName: "HDFC Bank",
    cardName: "HDFC Shoppers Stop Credit Card",
    annualFee: 500,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Shoppers+Stop",
    applyUrl: "https://bitli.in/7Sx8AWe",
    multipliers: [
      { category: "Shopping", rewardRate: 0.05, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "sbi-bpcl",
    bankName: "SBI Card",
    cardName: "SBI BPCL Credit Card",
    annualFee: 1499,
    minIncome: 500000,
    imageUrl: "https://placehold.co/320x200?text=SBI+BPCL",
    applyUrl: "https://bitli.in/r5cqthH",
    multipliers: [
      { category: "Fuel", rewardRate: 0.0725, maxCap: 2500 },
      { category: "Shopping", rewardRate: 0.025, maxCap: null },
      { category: "Other", rewardRate: 0.0025, maxCap: null },
    ],
  },
  {
    id: "sbi-miles",
    bankName: "SBI Card",
    cardName: "SBI Miles Credit Card",
    annualFee: 1499,
    minIncome: 600000,
    imageUrl: "https://placehold.co/320x200?text=SBI+Miles",
    applyUrl: "https://bitli.in/0kdZ0Ge",
    multipliers: [
      { category: "Travel", rewardRate: 0.05, maxCap: null },
      { category: "Dining", rewardRate: 0.03, maxCap: null },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "au-altura-plus",
    bankName: "AU Small Finance Bank",
    cardName: "AU Bank Altura Plus Credit Card",
    annualFee: 499,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=AU+Altura+Plus",
    applyUrl: "https://bitli.in/HfuxEx4",
    multipliers: [
      { category: "Grocery", rewardRate: 0.05, maxCap: 1000 },
      { category: "Online", rewardRate: 0.03, maxCap: 600 },
      { category: "Other", rewardRate: 0.015, maxCap: null },
    ],
  },
  {
    id: "sbi-irctc-rupay",
    bankName: "SBI Card",
    cardName: "SBI IRCTC Rupay Credit Card",
    annualFee: 500,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=SBI+IRCTC+RuPay",
    applyUrl: "https://bitli.in/fG3oxlm",
    multipliers: [
      { category: "Travel", rewardRate: 0.04, maxCap: 1000 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-airtel",
    bankName: "Axis Bank",
    cardName: "Axis Airtel Rupay Credit Card",
    annualFee: 500,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Airtel",
    applyUrl: "https://bitli.in/6NJJX2Z",
    multipliers: [
      { category: "Online", rewardRate: 0.10, maxCap: 250 },
      { category: "Dining", rewardRate: 0.10, maxCap: 250 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "axis-lic",
    bankName: "Axis Bank",
    cardName: "Axis LIC Signature Credit Card",
    annualFee: 1500,
    minIncome: 500000,
    imageUrl: "https://placehold.co/320x200?text=Axis+LIC",
    applyUrl: "https://bitli.in/0oxa9sm",
    multipliers: [
      { category: "Shopping", rewardRate: 0.03, maxCap: 750 },
      { category: "Utilities", rewardRate: 0.05, maxCap: 500 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "indusind-legend",
    bankName: "IndusInd Bank",
    cardName: "IndusInd Legend Credit Card",
    annualFee: 1999,
    minIncome: 600000,
    imageUrl: "https://placehold.co/320x200?text=IndusInd+Legend",
    applyUrl: "https://bitli.in/P5Az4h7",
    multipliers: [
      { category: "Travel", rewardRate: 0.05, maxCap: null },
      { category: "Dining", rewardRate: 0.04, maxCap: null },
      { category: "Shopping", rewardRate: 0.03, maxCap: null },
      { category: "Other", rewardRate: 0.015, maxCap: null },
    ],
  },
  {
    id: "idfc-first-power",
    bankName: "IDFC FIRST Bank",
    cardName: "IDFC First Power Credit Card",
    annualFee: 0,
    minIncome: 200000,
    imageUrl: "https://placehold.co/320x200?text=IDFC+First+Power",
    applyUrl: "https://www.idfcfirstbank.com/personal-banking/cards/credit-card/first-power-credit-card",
    multipliers: [
      { category: "Fuel", rewardRate: 0.05, maxCap: 600 },
      { category: "Shopping", rewardRate: 0.02, maxCap: 300 },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
  {
    id: "hdfc-bank-card",
    bankName: "HDFC Bank",
    cardName: "HDFC Bank Credit Card",
    annualFee: 500,
    minIncome: 240000,
    imageUrl: "https://placehold.co/320x200?text=HDFC+Bank+Card",
    applyUrl: "https://www.hdfcbank.com/personal/pay/cards/credit-cards",
    multipliers: [
      { category: "Shopping", rewardRate: 0.025, maxCap: 625 },
      { category: "Other", rewardRate: 0.0033, maxCap: null },
    ],
  },
  {
    id: "axis-magnus",
    bankName: "Axis Bank",
    cardName: "Axis Magnus Credit Card",
    annualFee: 10000,
    minIncome: 1800000,
    imageUrl: "https://placehold.co/320x200?text=Axis+Magnus",
    applyUrl: "https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-credit-card",
    multipliers: [
      { category: "Travel", rewardRate: 0.12, maxCap: null },
      { category: "Dining", rewardRate: 0.06, maxCap: null },
      { category: "Online", rewardRate: 0.04, maxCap: null },
      { category: "Other", rewardRate: 0.03, maxCap: null },
    ],
  },
  {
    id: "au-lit",
    bankName: "AU Small Finance Bank",
    cardName: "AU LIT Credit Card Store",
    annualFee: 0,
    minIncome: 300000,
    imageUrl: "https://placehold.co/320x200?text=AU+LIT",
    applyUrl: "https://bitli.in/4eZ9Nm4",
    multipliers: [
      { category: "Other", rewardRate: 0.0025, maxCap: null },
    ],
  },
  {
    id: "indusind-platinum",
    bankName: "IndusInd Bank",
    cardName: "IndusInd Platinum Credit Card",
    annualFee: 999,
    minIncome: 400000,
    imageUrl: "https://placehold.co/320x200?text=IndusInd+Platinum",
    applyUrl: "https://bitli.in/g5yRpRQ",
    multipliers: [
      { category: "Travel", rewardRate: 0.03, maxCap: null },
      { category: "Shopping", rewardRate: 0.02, maxCap: null },
      { category: "Other", rewardRate: 0.01, maxCap: null },
    ],
  },
];
